/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.apicurio.registry.demo.domain;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LogInput extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2943448398923940976L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LogInput\",\"namespace\":\"io.apicurio.registry.demo.domain\",\"fields\":[{\"name\":\"line\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":[\"long\",\"null\"]},{\"name\":\"identifier\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LogInput> ENCODER =
      new BinaryMessageEncoder<LogInput>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LogInput> DECODER =
      new BinaryMessageDecoder<LogInput>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LogInput> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LogInput> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LogInput> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LogInput>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LogInput to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LogInput from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LogInput instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LogInput fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence line;
  @Deprecated public java.lang.Long timestamp;
  @Deprecated public java.lang.CharSequence identifier;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LogInput() {}

  /**
   * All-args constructor.
   * @param line The new value for line
   * @param timestamp The new value for timestamp
   * @param identifier The new value for identifier
   */
  public LogInput(java.lang.CharSequence line, java.lang.Long timestamp, java.lang.CharSequence identifier) {
    this.line = line;
    this.timestamp = timestamp;
    this.identifier = identifier;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return line;
    case 1: return timestamp;
    case 2: return identifier;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: line = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: identifier = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'line' field.
   * @return The value of the 'line' field.
   */
  public java.lang.CharSequence getLine() {
    return line;
  }


  /**
   * Sets the value of the 'line' field.
   * @param value the value to set.
   */
  public void setLine(java.lang.CharSequence value) {
    this.line = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'identifier' field.
   * @return The value of the 'identifier' field.
   */
  public java.lang.CharSequence getIdentifier() {
    return identifier;
  }


  /**
   * Sets the value of the 'identifier' field.
   * @param value the value to set.
   */
  public void setIdentifier(java.lang.CharSequence value) {
    this.identifier = value;
  }

  /**
   * Creates a new LogInput RecordBuilder.
   * @return A new LogInput RecordBuilder
   */
  public static io.apicurio.registry.demo.domain.LogInput.Builder newBuilder() {
    return new io.apicurio.registry.demo.domain.LogInput.Builder();
  }

  /**
   * Creates a new LogInput RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LogInput RecordBuilder
   */
  public static io.apicurio.registry.demo.domain.LogInput.Builder newBuilder(io.apicurio.registry.demo.domain.LogInput.Builder other) {
    if (other == null) {
      return new io.apicurio.registry.demo.domain.LogInput.Builder();
    } else {
      return new io.apicurio.registry.demo.domain.LogInput.Builder(other);
    }
  }

  /**
   * Creates a new LogInput RecordBuilder by copying an existing LogInput instance.
   * @param other The existing instance to copy.
   * @return A new LogInput RecordBuilder
   */
  public static io.apicurio.registry.demo.domain.LogInput.Builder newBuilder(io.apicurio.registry.demo.domain.LogInput other) {
    if (other == null) {
      return new io.apicurio.registry.demo.domain.LogInput.Builder();
    } else {
      return new io.apicurio.registry.demo.domain.LogInput.Builder(other);
    }
  }

  /**
   * RecordBuilder for LogInput instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LogInput>
    implements org.apache.avro.data.RecordBuilder<LogInput> {

    private java.lang.CharSequence line;
    private java.lang.Long timestamp;
    private java.lang.CharSequence identifier;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.apicurio.registry.demo.domain.LogInput.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.line)) {
        this.line = data().deepCopy(fields()[0].schema(), other.line);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.identifier)) {
        this.identifier = data().deepCopy(fields()[2].schema(), other.identifier);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing LogInput instance
     * @param other The existing instance to copy.
     */
    private Builder(io.apicurio.registry.demo.domain.LogInput other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.line)) {
        this.line = data().deepCopy(fields()[0].schema(), other.line);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.identifier)) {
        this.identifier = data().deepCopy(fields()[2].schema(), other.identifier);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'line' field.
      * @return The value.
      */
    public java.lang.CharSequence getLine() {
      return line;
    }


    /**
      * Sets the value of the 'line' field.
      * @param value The value of 'line'.
      * @return This builder.
      */
    public io.apicurio.registry.demo.domain.LogInput.Builder setLine(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.line = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'line' field has been set.
      * @return True if the 'line' field has been set, false otherwise.
      */
    public boolean hasLine() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'line' field.
      * @return This builder.
      */
    public io.apicurio.registry.demo.domain.LogInput.Builder clearLine() {
      line = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public io.apicurio.registry.demo.domain.LogInput.Builder setTimestamp(java.lang.Long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public io.apicurio.registry.demo.domain.LogInput.Builder clearTimestamp() {
      timestamp = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'identifier' field.
      * @return The value.
      */
    public java.lang.CharSequence getIdentifier() {
      return identifier;
    }


    /**
      * Sets the value of the 'identifier' field.
      * @param value The value of 'identifier'.
      * @return This builder.
      */
    public io.apicurio.registry.demo.domain.LogInput.Builder setIdentifier(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.identifier = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'identifier' field has been set.
      * @return True if the 'identifier' field has been set, false otherwise.
      */
    public boolean hasIdentifier() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'identifier' field.
      * @return This builder.
      */
    public io.apicurio.registry.demo.domain.LogInput.Builder clearIdentifier() {
      identifier = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LogInput build() {
      try {
        LogInput record = new LogInput();
        record.line = fieldSetFlags()[0] ? this.line : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.identifier = fieldSetFlags()[2] ? this.identifier : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LogInput>
    WRITER$ = (org.apache.avro.io.DatumWriter<LogInput>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LogInput>
    READER$ = (org.apache.avro.io.DatumReader<LogInput>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.line);

    if (this.timestamp == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeLong(this.timestamp);
    }

    if (this.identifier == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.identifier);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.line = in.readString(this.line instanceof Utf8 ? (Utf8)this.line : null);

      if (in.readIndex() != 0) {
        in.readNull();
        this.timestamp = null;
      } else {
        this.timestamp = in.readLong();
      }

      if (in.readIndex() != 0) {
        in.readNull();
        this.identifier = null;
      } else {
        this.identifier = in.readString(this.identifier instanceof Utf8 ? (Utf8)this.identifier : null);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.line = in.readString(this.line instanceof Utf8 ? (Utf8)this.line : null);
          break;

        case 1:
          if (in.readIndex() != 0) {
            in.readNull();
            this.timestamp = null;
          } else {
            this.timestamp = in.readLong();
          }
          break;

        case 2:
          if (in.readIndex() != 0) {
            in.readNull();
            this.identifier = null;
          } else {
            this.identifier = in.readString(this.identifier instanceof Utf8 ? (Utf8)this.identifier : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










